raid:
  target: dev
  outputs:
    dev:
      type: databricks
      host: "{{ env_var('DATABRICKS_HOST') }}"
      http_path: "{{ env_var('DATABRICKS_HTTP_PATH') }}"
      token: "{{ env_var('DATABRICKS_TOKEN') }}"

      # Where dbt will create models (Unity Catalog)
      catalog: "{{ env_var('DATABRICKS_CATALOG', 'workspace') }}"
      schema: "{{ env_var('DBT_SCHEMA', 'raid') }}"

      threads: 1
