version: 2

models:
  - name: ops_processed_snapshots
    description: >
      Registry of processed snapshot files per account. Stores the authoritative processing order
      and an event-time sort key used to detect out-of-order snapshots. This table acts as the
      control plane for incremental downstream models (current selection, first_seen, events).

      Key concepts:
      - snapshot_order_no: Monotonic processing sequence per account (ingestion order).
      - event_sort_key: Deterministic event-time ordering key derived from snapshot metadata.
      - is_out_of_order: True when an incoming snapshot's event_time order would precede the
        latest previously processed snapshot for the same account.

    config:
      alias: silver_ops_processed_snapshots
      tags: ['contract']

    tests:
      - dbt_utils.unique_combination_of_columns:
          arguments:
            combination_of_columns:
              - account_name
              - source_file

      - dbt_utils.unique_combination_of_columns:
          arguments:
            combination_of_columns:
              - account_name
              - snapshot_date
              - snapshot_version
          config:
            severity: warn

      # Cheap invariants
      - dbt_utils.expression_is_true:
          arguments:
            expression: "snapshot_order_no >= 1"
          config:
            severity: warn

      - dbt_utils.expression_is_true:
          arguments:
            expression: "snapshot_version IS NULL OR snapshot_version >= 0"
          config:
            severity: warn

      # sanity checks
      - dbt_utils.expression_is_true:
          arguments:
            expression: "event_sort_key LIKE '________-____-%'"
          config:
            severity: warn

      - dbt_utils.unique_combination_of_columns:
          arguments:
            combination_of_columns: [account_name, snapshot_order_no]

    columns:
      - name: account_name
        description: >
          Account identifier parsed from snapshot metadata/path. Partition key for ordering and downstream processing.
        tests:
          - not_null

      - name: source_file
        description: >
          Unique snapshot file path for the account and snapshot. Used as the file-level identifier in downstream joins.
        tests:
          - not_null

      - name: snapshot_order_no
        description: >
          Monotonic processing-order sequence per account. Calculated incrementally as snapshots are ingested.
          Defines the authoritative processing order for downstream incremental models.
        tests:
          - not_null

      - name: event_sort_key
        description: >
          Deterministic event-time ordering key derived from snapshot_date, snapshot_version, and source_file.
          Used to detect out-of-order snapshots and to apply consistent event-time ordering in downstream models.
        tests:
          - not_null

      - name: is_out_of_order
        description: >
          True if the snapshot's event_sort_key is less than the maximum event_sort_key previously processed
          for the same account. Out-of-order snapshots are excluded from some downstream models.
        tests:
          - not_null

      - name: snapshot_ts
        description: >
          Timestamp when the snapshot was taken/ingested (from stg_champindex). Used for incremental cutoffs.
        tests:
          - not_null

      - name: snapshot_date
        description: >
          Business date represented by the snapshot (used in event_sort_key and deterministic ordering).

      - name: snapshot_version
        description: >
          Version number within the same snapshot_date (used in event_sort_key and deterministic ordering).

  - name: ops_quarantine_champindex_classified
    description: >
      Quarantine view for champindex staging rows flagged as invalid by stg_champindex__classified.
      Contains only rows where is_quarantined = true, with quarantine_reason and quarantine_bucket
      describing the first-match failure cause and high-level category.

      This is the operational debugging surface for row-level data quality issues (keys, lineage, domain, range).

    config:
      alias: silver_ops_quarantine_champindex_classified
      tags: ['contract']

    tests:
      - dbt_utils.expression_is_true:
          arguments:
            expression: "failure_reason IS NOT NULL"
          config:
            severity: warn

    columns:
      - name: failure_reason
        description: >
          Operational alias for quarantine_reason. Non-null for all rows in this quarantine view.
          Examples: KEY_NULL:account_name, LINEAGE_NULL:run_id, DOMAIN:affinity, RANGE:hp.
        tests:
          - not_null:
              config:
                severity: warn

      - name: quarantine_reason
        description: >
          Primary quarantine reason code emitted by stg_champindex__classified.
        tests:
          - not_null:
              config:
                severity: warn

      - name: quarantine_bucket
        description: >
          High-level quarantine category emitted by stg_champindex__classified.
        tests:
          - not_null:
              config:
                severity: warn
          - accepted_values:
              arguments:
                values: ["KEY", "LINEAGE", "MISSING_ATTR", "DOMAIN", "RANGE"]
              config:
                severity: warn

      - name: is_quarantined
        description: True for all rows in this quarantine view.
        tests:
          - accepted_values:
              arguments:
                values: [true]
              config:
                severity: warn

      # Passthrough columns from stg_champindex for debugging (documented, no tests)
      - name: account_name
        description: Account identifier from stg_champindex. May be NULL depending on failure_reason.

      - name: owned_champion_id
        description: Owned champion instance identifier from stg_champindex. May be NULL depending on failure_reason.

      - name: source_champion_id
        description: Champion type identifier from stg_champindex. May be NULL depending on failure_reason.

      - name: source_file
        description: Source file path from stg_champindex. May be NULL depending on failure_reason.

      - name: snapshot_ts
        description: Snapshot ingestion timestamp (from stg_champindex).

      - name: snapshot_date
        description: Snapshot business date (from stg_champindex).

      - name: snapshot_version
        description: Snapshot version number (from stg_champindex).

  - name: ops_quarantine_champindex_duplicates
    description: >
      Quarantine view for duplicate champindex rows dropped during file-grain deduplication.
      Contains only "loser" rows (rn > 1) from the dedupe ranking logic, for the grain:
      (account_name, owned_champion_id, source_file).

      This view ensures no silent row drops when stg_champindex__final selects rn = 1 winners.

    config:
      alias: silver_ops_quarantine_champindex_duplicates
      tags: ['contract']

    tests:
      - dbt_utils.expression_is_true:
          arguments:
            expression: "failure_reason IS NOT NULL"
          config:
            severity: warn

    columns:
      - name: failure_reason
        description: >
          Duplicate quarantine reason code. Emitted for all rows in this view.
        tests:
          - not_null:
              config:
                severity: warn
          - accepted_values:
              arguments:
                values:
                  - "DUPLICATE_KEY:account_name+owned_champion_id+source_file"
              config:
                severity: warn

      - name: duplicate_group_count
        description: >
          Number of rows in the duplicate group for the key (account_name, owned_champion_id, source_file).
        tests:
          - not_null:
              config:
                severity: warn

      - name: duplicate_row_number
        description: >
          Row-number assigned by dedupe ranking (rn). Losers are rn > 1.
        tests:
          - not_null:
              config:
                severity: warn

      # Passthrough columns (documented, no tests)
      - name: account_name
        description: Account identifier.

      - name: owned_champion_id
        description: Owned champion instance identifier.

      - name: source_file
        description: Source file path for the snapshot file.

      - name: snapshot_ts
        description: Snapshot ingestion timestamp.

      - name: snapshot_date
        description: Snapshot business date.

      - name: snapshot_version
        description: Snapshot version number.

  - name: ops_last_run_summary
    description: >
      Operational summary of the latest processed snapshot per account. Provides a single
      row per account capturing latest snapshot metadata, row counts for that snapshot,
      and key-quarantine counts. Designed for monitoring and as a lightweight input to
      gold operational dashboards.

    config:
      alias: silver_ops_last_run_summary
      tags: ['contract']

    tests:
      - dbt_utils.unique_combination_of_columns:
          arguments:
            combination_of_columns: [account_name]

    columns:
      - name: account_name
        description: Account identifier.
        tests: [not_null]

      - name: source_file
        description: Source file path for the latest snapshot selected for the account.
        tests: [not_null]

      - name: snapshot_ts
        description: Snapshot ingestion timestamp for the latest snapshot.
        tests: [not_null]

      - name: snapshot_date
        description: Business date represented by the latest snapshot.

      - name: snapshot_version
        description: Snapshot version within the snapshot_date for the latest snapshot.

      - name: snapshot_order_no
        description: Monotonic processing order number for the latest snapshot.
        tests: [not_null]

      - name: is_out_of_order
        description: Whether the latest snapshot is flagged as out-of-order.
        tests: [not_null]

      - name: champ_rows_in_snapshot
        description: Count of rows in stg_champindex for the latest snapshot file.
        tests: [not_null]

      - name: quarantine_key_rows_in_snapshot
        description: Count of quarantined rows with null keys for the latest snapshot file.
        tests: [not_null]

  - name: ops_out_of_order_snapshots
    description: >
      Operational view listing snapshot files flagged as out-of-order per account
      based on event_sort_key ordering in ops_processed_snapshots. These snapshots
      are typically excluded from downstream "current" and event derivations to
      preserve deterministic ordering.

    config:
      alias: silver_ops_out_of_order_snapshots
      tags: ['contract']

    tests:
      - dbt_utils.unique_combination_of_columns:
          arguments:
            combination_of_columns: [account_name, source_file]

    columns:
      - name: account_name
        description: Account identifier.
        tests: [not_null]

      - name: source_file
        description: Snapshot file path flagged as out-of-order.
        tests: [not_null]

      - name: snapshot_ts
        description: Snapshot ingestion timestamp.
        tests: [not_null]

      - name: snapshot_date
        description: Business date represented by the snapshot.

      - name: snapshot_version
        description: Snapshot version within snapshot_date.

      - name: snapshot_order_no
        description: Processing order number assigned to the snapshot for this account.
        tests: [not_null]

      - name: event_sort_key
        description: Event-time ordering key used to detect out-of-order snapshots.
        tests: [not_null]
